config/routes.rb
Railscp::Application.routes.draw do

  match 'api/v1/account/login' => "api#login", :as => :api_login
  match 'api/v1/account/logout' => "api#logout", :as => :api_logout
  match 'api/v1/account/status' => "api#status", :as => :api_status

  resources :operator_sessions
  resources :captive_portals do
    resources :allowed_traffics
    resources :local_users
    resources :online_users
  end

  match 'operator/login'  => "operator_sessions#new",     :as => :operator_login
  match 'operator/logout' => "operator_sessions#destroy", :as => :operator_logout

  match 'application/set_session_locale'

  match 'redirect' => 'redirections#redirect', :as => :redirect, :method => :get
  match 'authentication' => 'redirections#default_authentication_page',
        :as => :authentication, :method => :get
  match 'error' => 'redirections#default_error_page',
        :as => :error, :method => :get
  match 'login' => 'redirections#login', :as => :login, :method => :post
  match 'logout' => 'redirections#logout', :as => :logout, :method => :get

  match '/' => "redirections#redirect"
  match '*path' => "redirections#redirect"

end

app/models/allowed_traffic.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class AllowedTraffic < ActiveRecord::Base

  belongs_to :captive_portal

  validates_inclusion_of :protocol, :in => %w(tcp udp), :allow_nil => true, :allow_blank => true
  validates_format_of :source_mac_address, :with => /\A([0-9a-f]{2}:){5}[0-9a-f]{2}\Z/i, :allow_nil => true, :allow_blank => true
  validates_format_of :source_host, :with => /\A[a-zA-Z0-9:\-\.\/]+\Z/, :allow_nil => true, :allow_blank => true
  validates_numericality_of :source_port, :greater_than => 0, :less_than_or_equal_to => 65535,
                            :allow_nil => true, :allow_blank => true

  validates_format_of :destination_host, :with => /\A[a-zA-Z0-9:\-\.\/]+\Z/, :allow_nil => true, :allow_blank => true
  validates_numericality_of :destination_port, :greater_than => 0, :less_than_or_equal_to => 65535,
                            :allow_nil => true, :allow_blank => true

  attr_accessible :protocol, :source_mac_address, :source_host, :source_port, :destination_host, :destination_port, :note

  after_create {
    worker = MiddleMan.worker(:captive_portal_worker)
    worker.async_add_allowed_traffic(
        :args => {
            :cp_interface => self.captive_portal.cp_interface,
            :source_mac => self.source_mac_address,
            :source_host => self.source_host,
            :destination_host => self.destination_host,
            :protocol => self.protocol,
            :source_port => self.source_port,
            :destination_port => self.destination_port
        }
    )
  }

  before_update {
    old_allowed_traffic = AllowedTraffic.find( self.id )
    worker = MiddleMan.worker(:captive_portal_worker)
    worker.async_remove_allowed_traffic(
        :args => {
            :cp_interface => old_allowed_traffic.captive_portal.cp_interface,
            :source_mac => old_allowed_traffic.source_mac_address,
            :source_host => old_allowed_traffic.source_host,
            :destination_host => old_allowed_traffic.destination_host,
            :protocol => old_allowed_traffic.protocol,
            :source_port => old_allowed_traffic.source_port,
            :destination_port => old_allowed_traffic.destination_port
        }
    )
    worker.async_add_allowed_traffic(
        :args => {
            :cp_interface => self.captive_portal.cp_interface,
            :source_mac => self.source_mac_address,
            :source_host => self.source_host,
            :destination_host => self.destination_host,
            :protocol => self.protocol,
            :source_port => self.source_port,
            :destination_port => self.destination_port
        }
    )
  }

  before_destroy {
      # This could be invoked from a worker, so we must use async_ here to avoid deadlocks
    worker = MiddleMan.worker(:captive_portal_worker)
    worker.async_remove_allowed_traffic(
        :args => {
            :cp_interface => self.captive_portal.cp_interface,
            :source_mac => self.source_mac_address,
            :source_host => self.source_host,
            :destination_host => self.destination_host,
            :protocol => self.protocol,
            :source_port => self.source_port,
            :destination_port => self.destination_port
        }
    )
  }

end

app/controllers/allowed_traffics_controller.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class AllowedTrafficsController < ApplicationController
  layout "operators"

  before_filter :require_operator
  
  before_filter :load_captive_portal
  before_filter :load_allowed_traffic, :only => [ :show, :destroy, :edit, :update ]

  protected

  def load_captive_portal
    @captive_portal = CaptivePortal.find(params[:captive_portal_id])
  end

  def load_allowed_traffic
    @allowed_traffic = @captive_portal.allowed_traffics.find(params[:id])
  end

  public

  def index
    @allowed_traffics = @captive_portal.allowed_traffics.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @allowed_traffics }
    end
  end

  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @allowed_traffic }
    end
  end

  def new
    @allowed_traffic = @captive_portal.allowed_traffics.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @allowed_traffic }
    end
  end

  def edit
  end

  def create
    @allowed_traffic = @captive_portal.allowed_traffics.build(params[:allowed_traffic])

    respond_to do |format|
      if @allowed_traffic.save
        format.html {
          redirect_to(captive_portal_allowed_traffic_url(@captive_portal, @allowed_traffic),
                      :notice => 'Allowed traffic was successfully created.')
        }
        format.xml  { render :xml => @allowed_traffic, :status => :created, :location => @allowed_traffic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @allowed_traffic.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @allowed_traffic.update_attributes(params[:allowed_traffic])
        format.html {
          redirect_to(captive_portal_allowed_traffic_url(@captive_portal, @allowed_traffic),
                      :notice => 'Allowed traffic was successfully updated.')
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @allowed_traffic.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @allowed_traffic.destroy

    respond_to do |format|
      format.html {
        redirect_to(captive_portal_allowed_traffics_url(@captive_portal))
      }
      format.xml  { head :ok }
    end
  end
end

app/helpers/allowed_traffics_helper.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module AllowedTrafficsHelper
end

app/views/allowed_traffics/_form.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<fieldset class="form">
  <legend><%=t :allowed_traffic %></legend>

  <%= form_for([@captive_portal, @allowed_traffic]) do |f| %>
      <% if @allowed_traffic.errors.any? %>
          <h3 id="error_explanation" class="toggler atStart" style="color: #ff0000">
            <%= t(:error, :count => @allowed_traffic.errors.count) %>
          </h3>
          <h4 class="toggler atStart">
            <ul>
              <% @allowed_traffic.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </h4>
      <% end %>


      <p>
        <%= f.label :protocol %>
        <%= select :allowed_traffic,
                   :protocol,
                   [['tcp', 'tcp'], ['udp', 'udp']],
                   {:include_blank => 'None'}
        %>
      </p>
      <p>
        <%= f.label :source_mac_address %>
        <%= f.text_field :source_mac_address %>
      </p>
      <p>
        <%= f.label :source_host %>
        <%= f.text_field :source_host %>
      </p>
      <p>
        <%= f.label :source_port %>
        <%= f.text_field :source_port %>
      </p>
      <p>
        <%= f.label :destination_host %>
        <%= f.text_field :destination_host %>
      </p>
      <p>
        <%= f.label :destination_port %>
        <%= f.text_field :destination_port %>
      </p>
      <p>
        <%= f.label :note %>
        <%= f.text_field :note %>
      </p>

      <%= f.submit :class => :button %>

  <% end %>

</fieldset>

app/views/allowed_traffics/edit.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-editing_allowed_traffic"><%=t :editing_allowed_traffic %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:allowed_traffic), '#' %>
        <ul>
          <li>
            <%= link_to t(:show), captive_portal_allowed_traffic_path(@captive_portal, @allowed_traffic) %> 
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portal_allowed_traffics_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="editing_allowed_traffic">

      <%= render 'form' %>

    </div>
  </div>
</div>
<div class="clear"></div>

app/views/allowed_traffics/index.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-listing_allowed_traffics"><%=t :listing_allowed_traffics %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:allowed_traffics), '#' %>
        <ul>
          <li>
            <%= link_to t(:new), new_captive_portal_allowed_traffic_path(@captive_portal)  %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portal_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="listing_allowed_traffics">

      <table>
        <thead>
        <tr>
          <th><%=t :actions %></th>
          <th><%=t :protocol %></th>
          <th><%=t :source_mac_address %></th>
          <th><%=t :source_host %></th>
          <th><%=t :source_port %></th>
          <th><%=t :destination_host %></th>
          <th><%=t :destination_port %></th>
          <th><%=t :note %></th>
        </tr>
        </thead>
        <tbody>
        <% @allowed_traffics.each do |allowed_traffic| %>
            <tr class="<%= cycle("even", "odd") -%>">
              <td>
                <%=
                    link_to image_tag("show.png", :border => 0, :size => "16x16", :alt => t(:show)),
                            captive_portal_allowed_traffic_path(@captive_portal, allowed_traffic)
                %>
                <%=
                    link_to image_tag("edit.png", :border => 0, :size => "16x16", :alt => t(:edit)),
                            edit_captive_portal_allowed_traffic_path(@captive_portal, allowed_traffic)
                %>
                <%=
                    link_to image_tag("delete.png", :border => 0, :size => "16x16", :alt => t(:destroy)),
                            captive_portal_allowed_traffic_path(@captive_portal, allowed_traffic),
                            :confirm => t(:are_you_sure), :method => :delete
                %>
              </td>
              <td><%=h allowed_traffic.protocol %></td>
              <td><%=h allowed_traffic.source_mac_address %></td>
              <td><%=h allowed_traffic.source_host %></td>
              <td><%=h allowed_traffic.source_port %></td>
              <td><%=h allowed_traffic.destination_host %></td>
              <td><%=h allowed_traffic.destination_port %></td>
              <td><%=h allowed_traffic.note %></td>
            </tr>
        <% end %>
        </tbody>
        <tfoot>
        </tfoot>
      </table>
      
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/allowed_traffics/new.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-new_allowed_traffic"><%=t :new_allowed_traffic %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:back), captive_portal_allowed_traffics_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="new_allowed_traffic">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <%= render 'form' %>

    </div>
  </div>
</div>
<div class="clear"></div>

app/views/allowed_traffics/show.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-show_captive_portals"><%=t :allowed_traffics %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:allowed_traffics), '#' %>
        <ul>
          <li>
            <%= link_to t(:edit), edit_captive_portal_allowed_traffic_path(@captive_portal, @allowed_traffic) %>
          </li>
          <li>
            <%= link_to t(:destroy), captive_portal_allowed_traffic_path(@captive_portal, @allowed_traffic), :confirm => t(:are_you_sure), :method => :delete %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portal_allowed_traffics_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="show_captive_portals">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <tbody>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :protocol %></th>
          <td><%=h @allowed_traffic.protocol %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :source_mac_address %></th>
          <td><%=h @allowed_traffic.source_mac_address %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :source_host %></th>
          <td><%=h @allowed_traffic.source_host %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :source_port %></th>
          <td><%=h @allowed_traffic.source_port %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :destination_host %></th>
          <td><%=h @allowed_traffic.destination_host %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :destination_port %></th>
          <td><%=h @allowed_traffic.destination_port %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :note %></th>
          <td><%=h @allowed_traffic.note %></td>
        </tr>
        </tbody>
        <tfoot>
        </tfoot>
      </table>
    </div>
  </div>
</div>
<div class="clear"></div>