config/routes.rb
Railscp::Application.routes.draw do

  match 'api/v1/account/login' => "api#login", :as => :api_login
  match 'api/v1/account/logout' => "api#logout", :as => :api_logout
  match 'api/v1/account/status' => "api#status", :as => :api_status

  resources :operator_sessions
  resources :captive_portals do
    resources :allowed_traffics
    resources :local_users
    resources :online_users
  end

  match 'operator/login'  => "operator_sessions#new",     :as => :operator_login
  match 'operator/logout' => "operator_sessions#destroy", :as => :operator_logout

  match 'application/set_session_locale'

  match 'redirect' => 'redirections#redirect', :as => :redirect, :method => :get
  match 'authentication' => 'redirections#default_authentication_page',
        :as => :authentication, :method => :get
  match 'error' => 'redirections#default_error_page',
        :as => :error, :method => :get
  match 'login' => 'redirections#login', :as => :login, :method => :post
  match 'logout' => 'redirections#logout', :as => :logout, :method => :get

  match '/' => "redirections#redirect"
  match '*path' => "redirections#redirect"

end

app/models/online_user.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#noinspection RubyResolve
require 'digest/md5'

class OnlineUser < ActiveRecord::Base

  belongs_to :captive_portal

  # TODO: validate password format (?? How ?? We have to be consistent with others class password attribute)
  validates_presence_of :password

  validates_inclusion_of :radius, :in => [ true, false ]

  validates_numericality_of :session_timeout, :allow_nil => true
  validates_numericality_of :idle_timeout, :allow_nil => true

  validates_numericality_of :max_upload_bandwidth, :greater_than => 0, :allow_nil => true
  validates_numericality_of :max_download_bandwidth, :greater_than => 0, :allow_nil => true

  validates_numericality_of :uploaded_octets, :greater_than_or_equal_to => 0
  validates_numericality_of :downloaded_octets, :greater_than_or_equal_to => 0
  validates_numericality_of :uploaded_packets, :greater_than_or_equal_to => 0
  validates_numericality_of :downloaded_packets, :greater_than_or_equal_to => 0

  validates_format_of :mac_address, :with => /\A([0-9a-f]{2}:){5}[0-9a-f]{2}\Z/
  validates_format_of :ip_address,
                      :with => /\A((([0-9])|([1-9][0-9])|(1[0-9][0-9])|(2[0-4][0-9])|(25[0-5]))\.){3}([0-9])|([1-9][0-9])|(1[0-9][0-9])|(2[0-4][0-9])|(25[0-5])\Z/

  validates_uniqueness_of :ip_address
  validates_uniqueness_of :mac_address
  validates_uniqueness_of :cp_session_token

  attr_accessible :username, :password, :cp_session_token, :ip_address, :mac_address, :session_timeout, :idle_timeout,
                  :uploaded_octets, :downloaded_octets, :uploaded_packets, :downloaded_packets, :last_activity,
                  :max_upload_bandwidth, :max_download_bandwidth, :radius

  before_create {
      # Generates the cp_session_token. Where applicable this id it's used also as a unique RADIUS session id.
    self.cp_session_token = (Digest::MD5.hexdigest(Time.new.to_s + self.username + self.password + self.ip_address +
                                                       self.mac_address))[0..16]
  }

  after_create {
      # Let the user pass through the firewall...
    worker = MiddleMan.worker(:captive_portal_worker)
    worker.add_user(
        :args => {
            :cp_interface => self.captive_portal.cp_interface,
            :address => self.ip_address,
            :mac => self.mac_address,
            :max_upload_bandwidth => self.max_upload_bandwidth,
            :max_download_bandwidth => self.max_download_bandwidth
        }
    )
  }

  before_destroy {
    # This could be invoked from a worker, so we must use async_ here to
    # avoid deadlocks
    worker = MiddleMan.worker(:captive_portal_worker)
    worker.async_remove_user(
        :args => {
            :cp_interface => self.captive_portal.cp_interface,
            :address => self.ip_address,
            :mac => self.mac_address,
            :max_upload_bandwidth => self.max_upload_bandwidth,
            :max_download_bandwidth => self.max_download_bandwidth
        }
    )
  }

  def initialize(options = {})
    options[:uploaded_octets] ||= 0
    options[:downloaded_octets] ||= 0
    options[:uploaded_packets] ||= 0
    options[:downloaded_packets] ||= 0
    super(options)
    self.last_activity = Time.now
  end

  def update_activity!(uploaded_octets, downloaded_octets, uploaded_packets, downloaded_packets)
    if uploaded_octets != self.uploaded_octets
      self.uploaded_octets = uploaded_octets
      self.uploaded_packets = uploaded_packets
      # Last activity timestamp for a user should be updated only when she generates traffic
      self.last_activity = Time.now
    end
    
    if  downloaded_octets != self.downloaded_octets
      self.downloaded_octets = downloaded_octets
      self.downloaded_packets = downloaded_packets
    end
    
    unless self.save
      logger.error("Failed to update activity of user '#{self.username}'")
    end
  end

  def RADIUS_user?
    self.radius
  end

  def local_user?
    ! self.radius
  end

  def session_time_interval
    (Time.now - self.created_at).to_i
  end

  def last_activity_interval
    (Time.now - self.last_activity).to_i
  end

  def inactive?
    return false if self.idle_timeout.nil?
    self.last_activity_interval > self.idle_timeout
  end

  def expired?
    return false if self.session_timeout.nil?
    self.session_time_interval > self.session_timeout
  end

  def refresh!
    uploaded_octets, downloaded_octets = octets_counters
    uploaded_packets, downloaded_packets = packets_counters
    update_activity!(uploaded_octets, downloaded_octets, uploaded_packets, downloaded_packets)
  end

  protected
  
  def octets_counters
    begin
      worker = MiddleMan.worker(:captive_portal_worker)
      worker.get_user_bytes_counters(
          :args => {
              :cp_interface => self.captive_portal.cp_interface,
              :address => self.ip_address,
              :mac => self.mac_address
          }
      )
    # if something goes wrong return 0
    rescue BackgrounDRb::RemoteWorkerError
      return 0
    end
  end

  def packets_counters
    worker = MiddleMan.worker(:captive_portal_worker)
    worker.get_user_packets_counters(
        :args => {
            :cp_interface => self.captive_portal.cp_interface,
            :address => self.ip_address,
            :mac => self.mac_address
        }
    )
  end
end

app/controllers/online_users_controller.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class OnlineUsersController < ApplicationController
  layout "operators"

  before_filter :require_operator

  before_filter :load_captive_portal
  before_filter :load_online_user, :only => [ :show, :destroy ]

  protected

  def load_captive_portal
    @captive_portal = CaptivePortal.find(params[:captive_portal_id])
  end

  def load_online_user
    @online_user = @captive_portal.online_users.find(params[:id])
    @online_user.refresh! unless @online_user.nil?
  end

  public

  def index
    @online_users = @captive_portal.online_users.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @online_users }
    end
  end

  def show
    @online_user = @captive_portal.online_users.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @online_user }
    end
  end

  def destroy
    @captive_portal.deauthenticate_user(@online_user, RadiusAcctServer::SESSION_TERMINATE_CAUSE[:Forced_logout])
    @online_user.destroy

    respond_to do |format|
      format.html {
        redirect_to(captive_portal_online_users_url(@captive_portal))
      }
      format.xml  { head :ok }
    end
  end
end

app/helpers/online_users_helper.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module OnlineUsersHelper
end

app/views/online_users/index.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-listing_online_users"><%=t :listing_online_users %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:back), captive_portal_path(@captive_portal) %>
      </li>
    </ul>
    
    <div class="block" id="listing_online_users">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <thead>
        <tr>
          <th><%=t :actions %></th>
          <th><%=t :username %></th>
          <th><%=t :ip_address %></th>
          <th><%=t :mac_address %></th>
          <th><%=t :uploaded_octets %></th>
          <th><%=t :downloaded_octets %></th>
          <th><%=t :uploaded_packets %></th>
          <th><%=t :downloaded_packets %></th>
          <th><%=t :session_start %></th>
          <th><%=t :last_activity %></th>
        </tr>
        </thead>
        <tbody>
        <% @online_users.each do |online_user| %>
            <tr class="<%= cycle("even", "odd") -%>">
              <td>
                <% if !online_user.RADIUS_user? %>
                    <% local_user = @captive_portal.local_users.find_by_username(online_user.username) %>
                    <% if !local_user.nil? %>
                        <%= link_to image_tag("notes.png", :border=>0, :size => "16x16", :alt => t(:edit)),
                                    captive_portal_local_user_path(@captive_portal, local_user)
                        %>
                    <% end %>
                <% end %>
                <%=
                    link_to image_tag("delete.png", :border=>0, :size => "16x16", :alt => t(:destroy)),
                            captive_portal_online_user_path(@captive_portal, online_user),
                            :confirm => t(:are_you_sure), :method => :delete
                %>
              </td>
              <td>
                <%=
                    link_to h(online_user.username), captive_portal_online_user_path(@captive_portal, online_user)
                %>
              </td>
              <td><%=h online_user.ip_address %></td>
              <td><%=h online_user.mac_address %></td>
              <td><%=h number_to_human_size(online_user.uploaded_octets) %></td>
              <td><%=h number_to_human_size(online_user.downloaded_octets) %></td>
              <td><%=h number_to_human(online_user.uploaded_packets) %></td>
              <td><%=h number_to_human(online_user.downloaded_packets) %></td>
              <td><%= l(online_user.created_at, :format => :short) %></td>
              <td><%= l(online_user.last_activity, :format => :short) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <p class="meta">
        &nbsp;
      </p>

    </div>
  </div>
</div>
<div class="clear"></div>

app/views/online_users/show.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-show_online_user"><%=t :show_online_user %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:back), captive_portal_online_users_path(@captive_portal) %>
      </li>
    </ul>
    
    <div class="block" id="show_online_user">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <tbody>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :username %></th>
          <td><%=h @online_user.username %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :max_upload_bandwidth %></th>
          <td><%=h @online_user.max_upload_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :max_download_bandwidth %></th>
          <td><%=h @online_user.max_download_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :radius %></th>
          <td><%=h @online_user.radius %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :cp_session_token %></th>
          <td><%=h @online_user.cp_session_token %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :ip_address %></th>
          <td><%=h @online_user.ip_address %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :mac_address %></th>
          <td><%=h @online_user.mac_address %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :called_station_id %></th>
          <td><%= @online_user.called_station_id %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :session_timeout %></th>
          <td><%=h @online_user.session_timeout %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :idle_timeout %></th>
          <td><%=h @online_user.idle_timeout %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :uploaded_octets %></th>
          <td><%=h number_to_human_size(@online_user.uploaded_octets, :precision => 2) %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :downloaded_octets %></th>
          <td><%=h number_to_human_size(@online_user.downloaded_octets, :precision => 2) %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :uploaded_packets %></th>
          <td><%=h number_to_human(@online_user.uploaded_packets, :precision => 2) %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :downloaded_packets %></th>
          <td><%=h number_to_human(@online_user.downloaded_packets, :precision => 2) %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :session_start %></th>
          <td><%= l(@online_user.created_at, :format => :short) %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :last_activity %></th>
          <td><%= l(@online_user.last_activity, :format => :short) %></td>
        </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>
<div class="clear"></div>