config/routes.rb
Railscp::Application.routes.draw do

  match 'api/v1/account/login' => "api#login", :as => :api_login
  match 'api/v1/account/logout' => "api#logout", :as => :api_logout
  match 'api/v1/account/status' => "api#status", :as => :api_status

  resources :operator_sessions
  resources :captive_portals do
    resources :allowed_traffics
    resources :local_users
    resources :online_users
  end

  match 'operator/login'  => "operator_sessions#new",     :as => :operator_login
  match 'operator/logout' => "operator_sessions#destroy", :as => :operator_logout

  match 'application/set_session_locale'

  match 'redirect' => 'redirections#redirect', :as => :redirect, :method => :get
  match 'authentication' => 'redirections#default_authentication_page',
        :as => :authentication, :method => :get
  match 'error' => 'redirections#default_error_page',
        :as => :error, :method => :get
  match 'login' => 'redirections#login', :as => :login, :method => :post
  match 'logout' => 'redirections#logout', :as => :logout, :method => :get

  match '/' => "redirections#redirect"
  match '*path' => "redirections#redirect"

end

app/models/captive_portal.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class CaptivePortal < ActiveRecord::Base

  has_many :local_users, :dependent => :destroy
  has_many :online_users, :dependent => :destroy
  has_many :allowed_traffics, :dependent => :destroy
  has_one :radius_auth_server, :dependent => :destroy
  has_one :radius_acct_server, :dependent => :destroy

  # Default url to redirect clients to if session[:original_url] is not present
  DEFAULT_URL="http://openwisp.org/"
  # Parameter to be added to the redirection URL whenever OWMW don't return a complete URL
  OWMW_URL_PARAMETER="__owmw"
  
  # Cache for user redirections
  # This is not meant to be a replacement of Rails (pages / actions) cache: here "cached
  # redirection URLs" still needs to be completed with the ORIGINAL_URL param.
  @@redirection_url_cache = Cache.new(:expires_in => 1.minute)
  
  validates_format_of :name, :with => /\A[a-zA-Z][a-zA-Z0-9\.\-]*\Z/
  validates_uniqueness_of :name
  validates_uniqueness_of :cp_interface
  validates_format_of :cp_interface, :with => /\A[a-zA-Z][a-zA-Z0-9\.\-]*\Z/
  validates_format_of :wan_interface, :with => /\A[a-zA-Z][a-zA-Z0-9\.\-]*\Z/

  validates_format_of :redirection_url, :with => /\Ahttps{0,1}:\/\/[a-zA-Z0-9:<%%>_=&\?\.\-\/\.]*\Z/
  validates_format_of :error_url, :with => /\Ahttps{0,1}:\/\/[a-zA-Z0-9:<%%>_=&\?\.\-\/\.]*\Z/

  validates_numericality_of :local_http_port, :less_than_or_equal_to => 65535, :greater_than_or_equal_to => 0
  validates_numericality_of :local_https_port, :less_than_or_equal_to => 65535, :greater_than_or_equal_to => 0

  validates_numericality_of :default_session_timeout, :greater_than_or_equal_to => 60, :allow_blank => true
  validates_numericality_of :default_idle_timeout, :greater_than_or_equal_to => 60, :allow_blank => true

  validates_numericality_of :total_download_bandwidth, :greater_than => 100, :allow_blank => true
  validates_numericality_of :total_upload_bandwidth, :greater_than => 100, :allow_blank => true
  
  validates_numericality_of :default_download_bandwidth, :greater_than => 100, :allow_blank => true
  validates_numericality_of :default_upload_bandwidth, :greater_than => 100, :allow_blank => true

  validates_presence_of :default_download_bandwidth, :unless => Proc.new { self.total_download_bandwidth.blank? }
  validates_presence_of :default_upload_bandwidth, :unless => Proc.new { self.total_upload_bandwidth.blank? }

  attr_readonly :cp_interface, :wan_interface

  attr_accessible :name, :cp_interface, :wan_interface, :redirection_url, :error_url, :local_http_port,
                  :local_https_port, :default_session_timeout, :default_idle_timeout, :total_download_bandwidth,
                  :total_upload_bandwidth, :default_download_bandwidth, :default_upload_bandwidth, :hostname_on_url,
                  :radius_auth_server_attributes, :radius_acct_server_attributes, :mac_address_auth, :mac_address_auth_shared_secret

  accepts_nested_attributes_for :radius_acct_server, :allow_destroy => true,
                                :reject_if => proc { |attributes| attributes[:host].blank? }
  accepts_nested_attributes_for :radius_auth_server, :allow_destroy => true,
                                :reject_if => proc { |attributes| attributes[:host].blank? }

  before_destroy {
    worker = MiddleMan.worker(:captive_portal_worker)

    worker.remove_cp(
      :args => {
          :cp_interface => cp_interface
      }
    )
  }

  before_update {
    worker = MiddleMan.worker(:captive_portal_worker)

    # cp_interface is a readonly attribute so it wont be changed
    worker.remove_cp(
      :args => {
        :cp_interface => cp_interface
      }
    )
    
    # set default mac address shared secret if left empty
    if self.mac_address_auth_shared_secret == ''
      self.mac_address_auth_shared_secret = self.class.columns_hash['mac_address_auth_shared_secret'].default
    end
  }

  # Called after save on create and after "before_update" on update
  after_save {
    worker = MiddleMan.worker(:captive_portal_worker)
    
    # For some strange reason, the following call can't be synchronous: it will
    # fail because no CaptivePortal for "cp_interface" will be found.
    # This is weird because in the after_save callback a record for 
    # "cp_interface" should exists
    worker.async_add_cp(
      :args => {
        :cp_interface => cp_interface,
        :wan_interface => wan_interface,
        :local_http_port => local_http_port,
        :local_https_port => local_https_port,
        :total_upload_bandwidth => total_upload_bandwidth,
        :total_download_bandwidth => total_download_bandwidth,
        :default_upload_bandwidth => default_upload_bandwidth,
        :default_download_bandwidth => default_download_bandwidth
      }
    )
  }
  
  def compile_redirection_url(options = {})
    options[:mac_address] ||= ""
    options[:ip_address] ||= ""
    options[:original_url] ||= ""

    # Fetch redirection url from cache
    url = @@redirection_url_cache.fetch("#{options[:mac_address]}-#{options[:ip_address]}") do
      # Cache miss
      begin
        if OWMW["url"].present? and options[:mac_address].present?
             
          # If OWMW is configured, get redirection URL from it.
          if (dynamic_url = AssociatedUser.site_url_by_user_mac_address(options[:mac_address]))
            if dynamic_url.match /\Ahttps{0,1}:\/\//
              _url = dynamic_url
            else
              # If what we obtained from OWMW isn't an URL, add it to the default redirection URL
              # This way we can add parameters to default redirection URL
              _url = redirection_url +
                  (redirection_url.include?('?') ? '&' : '?') + "#{OWMW_URL_PARAMETER}=" +
                  URI.escape(dynamic_url, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
            end
          else
            _url = redirection_url
          end
        else
          _url = redirection_url
        end
        if self.hostname_on_url and ( ap_hostname = AssociatedUser.access_point_hostname_by_user_mac_address(options[:mac_address]))
           _url = _url + "&HOSTNAME="+ap_hostname
           Rails.logger.error "Redirection URL: '#{_url}'"
        end
      rescue Exception => e
        _url = redirection_url
        Rails.logger.error "Problem compiling redirection URL: '#{e}'"
      end
      
      _url.gsub!(/<%\s*MAC_ADDRESS\s*%>/, URI.escape(options[:mac_address], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))
      _url.gsub!(/<%\s*IP_ADDRESS\s*%>/, URI.escape(options[:ip_address], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))
      
      # Cache this URL and return it
      _url
    end
        
    url.gsub!(/<%\s*ORIGINAL_URL\s*%>/, URI.escape(options[:original_url], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))

    url
  end

  def compile_error_url(options = {})
    url = error_url

    options[:mac_address] ||= ""
    options[:ip_address] ||= ""
    options[:original_url] ||= ""
    if options[:message].nil? or options[:message].blank?
      options[:message] = I18n.t(:no_message)
    end

    url.gsub!(/<%\s*MAC_ADDRESS\s*%>/, URI.escape(options[:mac_address], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))
    url.gsub!(/<%\s*IP_ADDRESS\s*%>/, URI.escape(options[:ip_address], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))
    url.gsub!(/<%\s*ORIGINAL_URL\s*%>/, URI.escape(options[:original_url], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))
    url.gsub!(/<%\s*MESSAGE\s*%>/, URI.escape(options[:message], Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")))

    url
  end

  def authenticate_user(username, password, client_ip, client_mac, timeout=false)
    # TO DO: Radius request offload ... (sync for auth, async for acct)
    radius = false
    reply = Hash.new
    
    if self.mac_address_auth and (username.nil? or username.empty?) and (password.nil? or password.empty?)
      username = client_mac
      password = self.mac_address_auth_shared_secret
    end

    # Check if user is already auth'ed on with same mac address
    unless online_users.where(:username => username, :mac_address => client_mac).empty?
      unless self.mac_address_auth
        return [ nil, I18n.t(:already_logged_in) ]
      else
        online_users.where(:username => username, :mac_address => client_mac).destroy_all
      end
    end
    
    # First look in local user
    local_user = local_users.where(:username => username).first
    if !local_user.nil?
      if local_user.check_password(password)
        # Password is valid, check if the user can log in

        ## Is the user disabled?
        if local_user.disabled?
          reply[:authenticated] = false
          reply[:message] = local_user.disabled_message
        end

        ## Is the user already logged in and multiple login are not allowed for him?
        if reply[:authenticated].nil? and !local_user.allow_concurrent_login? and
            online_users.count(:conditions => {:username => username}) > 0
          reply[:authenticated] = false
          reply[:message] = I18n.t(:concurrent_login_not_allowed)
        end

        ## Is a good guy, grant him/her access
        if reply[:authenticated].nil?
          reply[:authenticated] = true
          reply[:message] = ""

app/controllers/captive_portals_controller.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class CaptivePortalsController < ApplicationController
  layout "operators"

  before_filter :require_operator

  before_filter :load_captive_portal, :only => [ :show, :destroy, :edit, :update ]

  protected

  def load_captive_portal
    @captive_portal = CaptivePortal.find(params[:id])
  end

  public

  def index
    @captive_portals = CaptivePortal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @captive_portals }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @captive_portal }
    end
  end

  def new
    @captive_portal = CaptivePortal.new
    @captive_portal.radius_auth_server = RadiusAuthServer.new
    @captive_portal.radius_acct_server = RadiusAcctServer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @captive_portal }
    end
  end

  def edit
    @captive_portal.radius_auth_server = RadiusAuthServer.new if @captive_portal.radius_auth_server.nil?
    @captive_portal.radius_acct_server = RadiusAcctServer.new if @captive_portal.radius_acct_server.nil?
  end

  def create
    @captive_portal = CaptivePortal.new(params[:captive_portal])

    @captive_portal.radius_auth_server = RadiusAuthServer.new if @captive_portal.radius_auth_server.nil?
    @captive_portal.radius_acct_server = RadiusAcctServer.new if @captive_portal.radius_acct_server.nil?
    
    respond_to do |format|
      if @captive_portal.save
        format.html { redirect_to(@captive_portal, :notice => 'Captive portal was successfully created.') }
        format.xml  { render :xml => @captive_portal, :status => :created, :location => @captive_portal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @captive_portal.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    
    respond_to do |format|
      if @captive_portal.update_attributes(params[:captive_portal])
        format.html { redirect_to(captive_portal_url, :notice => 'Captive portal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @captive_portal.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @captive_portal.destroy

    respond_to do |format|
      format.html { redirect_to(captive_portals_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/captive_portal_helper.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
module CaptivePortalHelper
end

app/helpers/captiveportal_helper.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module CaptiveportalHelper
end

app/views/captive_portals/edit.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-editing_captive_portal"><%=t :editing_captive_portal %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:captive_portal), '#' %>
        <ul>
          <li>
            <%= link_to t(:show), @captive_portal %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portals_path %>
      </li>
    </ul>

    <div class="block" id="editing_captive_portal">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <%= render 'form' %>
      
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/captive_portals/index.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-listing_captive_portals"><%=t :listing_captive_portals %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:captive_portals), '#' %>
        <ul>
          <li>
            <%= link_to t(:new), new_captive_portal_path %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), :back %>
      </li>
    </ul>

    <div class="block" id="listing_captive_portals">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <thead>
        <tr>
          <th><%=t :actions %></th>
          <th><%=t :name %></th>
          <th><%=t :cp_interface %></th>
          <th><%=t :wan_interface %></th>
          <th><%=t :local_users %></th>
          <th><%=t :allowed_traffics %></th>
          <th><%=t :online_users %></th>
        </tr>
        </thead>
        <tbody>
        <% @captive_portals.each do |captive_portal| %>
            <tr class="<%= cycle("even", "odd") -%>">
              <td>
                <%=
                    link_to image_tag("edit.png", :border=>0, :size => "16x16", :alt => t(:edit)),
                            edit_captive_portal_path(captive_portal)
                %>
                <%=
                    link_to image_tag("delete.png", :border=>0, :size => "16x16", :alt => t(:destroy)),
                            captive_portal,
                            :confirm => t(:are_you_sure), :method => :delete
                %>
              </td>
              <td><%= link_to h(captive_portal.name), captive_portal %></td>
              <td><%=h captive_portal.cp_interface %></td>
              <td><%=h captive_portal.wan_interface %></td>
              <td>
                <%= link_to h(captive_portal.local_users.count),
                            captive_portal_local_users_path(captive_portal)
                %>
              </td>
              <td>
                <%= link_to h(captive_portal.allowed_traffics.count),
                            captive_portal_allowed_traffics_path(captive_portal)
                %>
              </td>
              <td>
                <%= link_to h(captive_portal.online_users.count),
                            captive_portal_online_users_path(captive_portal)
                %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/captive_portals/new.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-new_captive_portal"><%=t :new_captive_portal %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:back), captive_portals_path %>
      </li>
    </ul>

    <div class="block" id="new_captive_portal">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <%= render 'form' %>

    </div>
  </div>
</div>
<div class="clear"></div>

app/views/captive_portals/show.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-show_captive_portal"><%=t :show_captive_portal %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:captive_portal), '#' %>
        <ul>
          <li>
            <%= link_to t(:edit), edit_captive_portal_path(@captive_portal) %>
          </li>
          <li>
            <%= link_to t(:destroy), captive_portal_path(@captive_portal), :confirm => t(:are_you_sure), :method => :delete %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:local_users), '#' %>
        <ul>
          <li>
            <%= link_to t(:list), captive_portal_local_users_path(@captive_portal) %>
          </li>
          <li>
            <%= link_to t(:new), new_captive_portal_local_user_path(@captive_portal) %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:allowed_traffics), '#' %>
        <ul>
          <li>
            <%= link_to t(:list), captive_portal_allowed_traffics_path(@captive_portal) %>
          </li>
          <li>
            <%= link_to t(:new), new_captive_portal_allowed_traffic_path(@captive_portal) %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:online_users), '#' %>
        <ul>
          <li>
            <%= link_to t(:list), captive_portal_online_users_path(@captive_portal) %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portals_path %>
      </li>
    </ul>

    <div class="block" id="show_captive_portal">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <tbody>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :name %></th>
          <td><%=h @captive_portal.name %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :cp_interface %></th>
          <td><%=h @captive_portal.cp_interface %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :wan_interface %></th>
          <td><%=h @captive_portal.wan_interface %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :redirection_url %></th>
          <td><%=h @captive_portal.redirection_url %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :hostname_on_url %></th>
          <td><%=h @captive_portal.hostname_on_url ? t(:yes) : t(:no) %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :error_url %></th>
          <td><%=h @captive_portal.error_url %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :local_http_port %></th>
          <td><%=h @captive_portal.local_http_port %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :local_https_port %></th>
          <td><%=h @captive_portal.local_https_port %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :default_session_timeout %></th>
          <td><%=h @captive_portal.default_session_timeout %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :default_idle_timeout %></th>
          <td><%=h @captive_portal.default_idle_timeout %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :default_upload_bandwidth %></th>
          <td><%=h @captive_portal.default_upload_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :default_download_bandwidth %></th>
          <td><%=h @captive_portal.default_download_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :total_upload_bandwidth %></th>
          <td><%=h @captive_portal.total_upload_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :total_download_bandwidth %></th>
          <td><%=h @captive_portal.total_download_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :mac_address_auth_enabled %></th>
          <td><%=h @captive_portal.mac_address_auth ? t(:yes) : t(:no) %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="clear"></div>