config/routes.rb
Railscp::Application.routes.draw do

  match 'api/v1/account/login' => "api#login", :as => :api_login
  match 'api/v1/account/logout' => "api#logout", :as => :api_logout
  match 'api/v1/account/status' => "api#status", :as => :api_status

  resources :operator_sessions
  resources :captive_portals do
    resources :allowed_traffics
    resources :local_users
    resources :online_users
  end

  match 'operator/login'  => "operator_sessions#new",     :as => :operator_login
  match 'operator/logout' => "operator_sessions#destroy", :as => :operator_logout

  match 'application/set_session_locale'

  match 'redirect' => 'redirections#redirect', :as => :redirect, :method => :get
  match 'authentication' => 'redirections#default_authentication_page',
        :as => :authentication, :method => :get
  match 'error' => 'redirections#default_error_page',
        :as => :error, :method => :get
  match 'login' => 'redirections#login', :as => :login, :method => :post
  match 'logout' => 'redirections#logout', :as => :logout, :method => :get

  match '/' => "redirections#redirect"
  match '*path' => "redirections#redirect"

end

app/models/local_user.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class LocalUser < ActiveRecord::Base

  belongs_to :captive_portal

  validates_format_of :username, :with => /\A[0-9a-zA-Z:_\.\s\+\-]+\Z/
  validates_length_of :username, :within => 6..32
  validates_uniqueness_of :username, :scope => [ :captive_portal_id ]

  validates_format_of :password, :with => /\A[0-9a-zA-Z:_\.\s\+\-]+\Z/
  validates_length_of :password, :within => 8..32

  validates_numericality_of :max_upload_bandwidth, :greater_than => 0,
                            :allow_nil => true, :allow_blank => true
  validates_numericality_of :max_download_bandwidth, :greater_than => 0,
                            :allow_nil => true, :allow_blank => true

  validates_presence_of :disabled_message, :if => "disabled?"

  attr_readonly :username

  attr_accessible :username, :password, :max_upload_bandwidth, :max_download_bandwidth, :disabled, :disabled_message,
                  :allow_concurrent_login

  # Simple as can be :-D
  def check_password(password)
    self.password == password
  end

end

app/controllers/local_users_controller.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class LocalUsersController < ApplicationController
  layout "operators"

  before_filter :require_operator

  before_filter :load_captive_portal
  before_filter :load_local_user, :only => [ :show, :destroy, :edit, :update ]

  protected

  def load_captive_portal
    @captive_portal = CaptivePortal.find(params[:captive_portal_id])
  end

  def load_local_user
    @local_user = @captive_portal.local_users.find(params[:id])
  end

  public

  def index
    @local_users = @captive_portal.local_users.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @local_users }
    end
  end

  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @local_user }
    end
  end

  def new
    @local_user = @captive_portal.local_users.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @local_user }
    end
  end

  def edit
  end

  def create
    @local_user = @captive_portal.local_users.build(params[:local_user])

    respond_to do |format|
      if @local_user.save
        format.html {
          redirect_to(captive_portal_local_user_url(@captive_portal, @local_user),
                      :notice => 'Local user was successfully created.')
        }
        format.xml  { render :xml => @local_user, :status => :created, :location => @local_user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @local_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @local_user.update_attributes(params[:local_user])
        format.html {
          redirect_to(captive_portal_local_user_url(@captive_portal, @local_user), 
                      :notice => 'Local user was successfully updated.')
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @local_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @local_user.destroy

    respond_to do |format|
      format.html {
        redirect_to(captive_portal_local_users_url(@captive_portal))
      }
      format.xml  { head :ok }
    end
  end
end

app/helpers/local_users_helper.rb
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module LocalUsersHelper
end

app/views/local_users/_form.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<fieldset class="form">
  <legend><%=t :local_user %></legend>

  <%= form_for([@captive_portal, @local_user]) do |f| %>
      <% if @local_user.errors.any? %>
          <h3 id="error_explanation" class="toggler atStart" style="color: #ff0000">
            <%= pluralize(@local_user.errors.count, "error") %>
          </h3>
          <h4 class="toggler atStart">
            <ul>
              <% @local_user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </h4>
      <% end %>

      <p>
        <%= f.label :username %>
        <%= f.text_field :username %>
      </p>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :max_upload_bandwidth %>
        <%= f.number_field :max_upload_bandwidth, :step => 1024, :min => 0 %>
      </p>
      <p>
        <%= f.label :max_download_bandwidth %>
        <%= f.number_field :max_download_bandwidth, :step => 1024, :min => 0 %>
      </p>
      <p>
        <%= f.label :disabled %>
        <%= f.check_box :disabled %>
      </p>
      <p>
        <%= f.label :disabled_message %>
        <%= f.text_field :disabled_message %>
      </p>

      <p>
        <%= f.label :allow_concurrent_login %>
        <%= f.check_box :allow_concurrent_login %>
      </p>

      <%= f.submit :class => :button %>

  <% end %>

</fieldset>

app/views/local_users/edit.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-editing_local_user"><%=t :editing_local_user %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:local_user), '#' %>
        <ul>
          <li>
            <%= link_to t(:show), captive_portal_local_user_path(@captive_portal, @local_user) %> 
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back),captive_portal_local_users_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="editing_local_user">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <%= render 'form' %>

    </div>
  </div>
</div>
<div class="clear"></div>

app/views/local_users/index.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-listing_local_users"><%=t :listing_local_users %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:local_users), '#' %>
        <ul>
          <li>
            <%= link_to t(:new), new_captive_portal_local_user_path(@captive_portal) %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portal_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="listing_local_users">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <thead>
        <tr>
          <th><%=t :actions %></th>
          <th><%=t :username %></th>
          <th><%=t :max_upload_bandwidth %></th>
          <th><%=t :max_download_bandwidth %></th>
          <th><%=t :disabled %></th>
        </tr>
        </thead>
        <tbody>
        <% @local_users.each do |local_user| %>
            <tr class="<%= cycle("even", "odd") -%>">
              <td>
                <%=
                    link_to image_tag("edit.png", :border=>0, :size => "16x16", :alt => t(:edit)),
                            edit_captive_portal_local_user_path(@captive_portal, local_user)
                %>
                <%=
                    link_to image_tag("delete.png", :border=>0, :size => "16x16", :alt => t(:destroy)),
                            captive_portal_local_user_path(@captive_portal, local_user),
                            :confirm => t(:are_you_sure), :method => :delete
                %>
              </td>
              <td>
                <%= link_to h(local_user.username),
                            captive_portal_local_user_path(@captive_portal, local_user)
                %>
              </td>
              <td><%=h local_user.max_upload_bandwidth %></td>
              <td><%=h local_user.max_download_bandwidth %></td>
              <td><%=t local_user.disabled ? :yes : :no %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>
<div class="clear"></div>

app/views/local_users/new.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">
  <div class="box">
    <h2>
      <a href="#" id="toggle-new_local_user"><%=t :new_local_user %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:back), captive_portal_local_users_path(@captive_portal) %>
      </li>
    </ul>

    <div class="block" id="new_local_user">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <%= render 'form' %>

      <p class="meta">
        <%= link_to t(:back), :back %>
      </p>
      
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/local_users/show.html.erb
<%#
# This file is part of the OpenWISP Captive Portal Manager
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_16">

  <div class="box">
    <h2>
      <a href="#" id="toggle-show_local_user"><%=t :show_local_user %></a>
    </h2>
    <ul class="nav main">
      <li>
        <%= link_to t(:local_user), '#' %>
        <ul>
          <li>
            <%= link_to t(:edit), edit_captive_portal_local_user_path(@captive_portal, @local_user) %>
          </li>
          <li>
            <%= link_to t(:destroy), captive_portal_local_user_path(@captive_portal, @local_user), :confirm => t(:are_you_sure), :method => :delete %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(:back), captive_portal_local_users_path(@captive_portal) %>
      </li>
    </ul>
    
    <div class="block" id="show_local_user">

      <p class="meta" id="notice"><%= notice %>&nbsp;</p>

      <table>
        <tbody>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :username %></th>
          <td><%=h @local_user.username %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :max_upload_bandwidth %></th>
          <td><%=h @local_user.max_upload_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :max_download_bandwidth %></th>
          <td><%=h @local_user.max_download_bandwidth %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :disabled %></th>
          <td><%=t @local_user.disabled ? :yes : :no %></td>
        </tr>
        <tr class="<%= cycle("even", "odd") -%>">
          <th><%=t :disabled_message %></th>
          <td><%=h @local_user.disabled_message %></td>
        </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>
<div class="clear"></div>